# This is a basic workflow to help you get started with Actions

name: github actions demo success with badges

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "test-actions" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      branch:
        description: 'Branch'
        type: choice
        options:
          - staging-torrey
          - staging-legacy-torrey
          - sandbox-torrey
        default: staging
      environment:
        description: 🌎️ Environment
        type: choice
        default: staging
        options:
          - staging-torrey
          - staging-legacy-torrey
          - sandbox-torrey


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      #generate a badge for this run
      - name: Create Badge orange
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 222c4b03cc18f8ea0a0d20aba1a02621
          filename: badges-demo-orange.json
          label: ${{ format('{0} / environment {1} / branch {2}', github.workflow, github.event.inupts.environment ) }}


          label: environment
          message: ${{ github.event.inputs.environment }}
          color: orange

      #generate a badge for this run
      - name: Create Badge red
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 222c4b03cc18f8ea0a0d20aba1a02621
          filename: badges-demo-red.json
          label: branch
          message: ${{ github.event.inputs.branch }}
          color: red

      

  actual-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      #assume everything before now was successful
      - name: force success
        run: |
          echo something #zero return code incidates success
